language: java

jdk:
  - oraclejdk8

script:
  # Verify includes checkstyle, license and animal sniffer.
  - mvn verify javadoc:javadoc site
  - mvn test jacoco:report coveralls:report -Pcoveralls --fail-never

cache:
  directories:
    - $HOME/.m2
